SuitSupply/Controllers/ProductsWebPageController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.IO;
using System.Web.Mvc;
using SuitsupplyClassLibrary;

namespace SuitSupplyREST.Controllers
{

    [HandleError(ExceptionType = typeof(Exception), Master = "Error", View = "Index")]
    public class ProductsWebPageController : Controller
    {
        // Interfaces
        IProductContainer db;
        ILogWriter lg;
        public ProductsWebPageController()
        {
            db = new ProductContainer();
            lg = new LogWriter();
        }
        public ProductsWebPageController(IProductContainer context, ILogWriter LgWr)
        {
            db = context;
            lg = LgWr;
        }
        // GET: ProductsWebPage
        public async Task<ActionResult> Index()
        {
            return View(await db.GetAllProducts());
        }

        // GET: ProductsWebPage/Details/5
        public async Task<ActionResult> Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.GetProduct(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // GET: ProductsWebPage/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: ProductsWebPage/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Create([Bind(Include = "Id,Name,Price")] Product product, HttpPostedFileBase file)
        {
            product.LastUpdated = DateTime.Now;
            if (ModelState.IsValid)
            {
                product.Photo = GetPhotoOrBytes(file, product.Id);

                await db.InsertProduct(product);
                lg.WriteMessage(String.Format("Product with ID {0} is created", product.Id));
                return RedirectToAction("Index");
            }

            return View(product);
        }

        // GET: ProductsWebPage/Edit/5
        public async Task<ActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.GetProduct(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: ProductsWebPage/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit([Bind(Include = "Id,Name,Price,LastUpdated")] Product product, HttpPostedFileBase file)
        {
            product.LastUpdated = DateTime.Now;
            if (ModelState.IsValid)
            {
                product.Photo = GetPhotoOrBytes(file, product.Id);
                await db.EditProduct(product);
                lg.WriteMessage(String.Format("Product with ID {0} is edited", product.Id));
                return RedirectToAction("Index");
            }
            return View(product);
        }

        // GET: ProductsWebPage/Delete/5
        public async Task<ActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Product product = await db.GetProduct(id);
            if (product == null)
            {
                return HttpNotFound();
            }
            return View(product);
        }

        // POST: ProductsWebPage/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeleteConfirmed(int id)
        {
            await db.DeleteProduct(id);
            lg.WriteMessage(String.Format("Product with ID {0} is deleted", id));
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //override onexception method
        protected override void OnException(ExceptionContext filterContext)
        {
            Exception exception = filterContext.Exception;
            //Logging the Exception
            lg.WriteError(exception);
            filterContext.ExceptionHandled = true;
            
            var Result = this.View("Error", new HandleErrorInfo(exception,
               filterContext.RouteData.Values["controller"].ToString(),
                filterContext.RouteData.Values["action"].ToString()));
            filterContext.Result = Result;

        }

        /// <summary>
        /// render image based on exisitng bytes
        /// no async operations 
        /// </summary>
        /// <param name="id"> id of product</param>
        /// <returns></returns>
        public ActionResult RenderImage(int id)
        {
            return File(GetBytes(id), "image/png");
        }
        /// <summary>
        /// Get Bytes of existing Photo by id
        /// </summary>
        /// <param name="id"> id of product</param>
        /// <returns></returns>
        private byte[] GetBytes(int id)
        {
            Product prod = db.GetProductWithNoCache(id);
            return prod.Photo;
        }
        /// <summary>
        /// Get Bytes of existing Photo or push existed bytes to model
        /// no async methods here - otherwise EF can clinch about data state
        /// </summary>
        /// <param name="file"> control from view</param>
        /// <param name="id"> id of product</param>
        /// <returns></returns>
        private byte[] GetPhotoOrBytes(HttpPostedFileBase file, int id)
        {
            if (file != null && file.ContentLength > 0)
            {
                byte[] FileArray;
                using (var reader = new System.IO.BinaryReader(file.InputStream))
                {
                    FileArray = reader.ReadBytes(file.ContentLength);
                }
                return FileArray;
            }
            else if (id != 0 && db.GetProductWithNoCache(id) != null)
            {
                return GetBytes(id);
            }
            else { return null; }
        }
    }
}

SuitSupply/Views/ProductsWebPage/Create.cshtml
@model SuitsupplyClassLibrary.Product

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm("Create", "ProductsWebPage", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>



        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <!-- we accept only png and jpg-->
                <input type="file" name="file" id="file" accept=".png, .jpg" onchange="checkfile(this);" /><br><br>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SuitSupply/Views/ProductsWebPage/Delete.cshtml
@model SuitsupplyClassLibrary.Product

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

    
        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>
         
        <dd>
@if (Model.Photo != null && Model.Photo.Length > 0)
{
            <img class="Bigmage" src="@Url.Action("RenderImage", new { id = Model.Id })" />
}
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

SuitSupply/Views/ProductsWebPage/Details.cshtml
@model SuitsupplyClassLibrary.Product

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
         

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastUpdated)
        </dd>


        <dt>
            @Html.DisplayNameFor(model => model.Photo)
        </dt>

        <dd>
@if (Model.Photo != null && Model.Photo.Length > 0)
{
            <img class="Bigmage" src="@Url.Action("RenderImage", new { id = Model.Id })" />
}
        </dd>
    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

SuitSupply/Views/ProductsWebPage/Edit.cshtml
@model SuitsupplyClassLibrary.Product

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm("Edit", "ProductsWebPage", null, FormMethod.Post, new { enctype = "multipart/form-data" }))
{ 
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Product</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastUpdated, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
              <p class="LastUpdateLabel"> @Html.Encode(Model.LastUpdated)</p>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label col-md-2" })
            <table>

                @if (Model.Photo != null && Model.Photo.Length > 0)
                {
                    <tr>
                        <td>
                            <br />
                            <img class="BigImage" src="@Url.Action("RenderImage", new { id = Model.Id })" />
                            <br />
                        </td>
                    </tr>
                }
                <tr>
                    <td>
                        <input type="file" name="file" id="file" accept=".png, .jpg" onchange="checkfile(this);" />
                        <br/> 
                    </td>
                </tr>
            </table>
        </div>

       
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

SuitSupply/Views/ProductsWebPage/Index.cshtml
@model IEnumerable<SuitsupplyClassLibrary.Product>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Photo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.LastUpdated)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Name)
        </td>
        <td>
            @if (item.Photo != null && item.Photo.Length > 0)
            {
            <img class="LittleImage" src="@Url.Action("RenderImage", new { id = item.Id })" />
            }
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Price)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LastUpdated)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.Id })
        </td>
    </tr>
}

</table>